name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    strategy:
      xcode: ['/Applications/Xcode_11.1.app/Contents/Developer']
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: xcode-select -v
    - name: Run tests
      run: xcodebuild -workspace Clipy.xcworkspace -scheme Clipy -destination 'platform=macOS' clean test
