name: Swift

on: [push]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Show Xcode Version
      run: xcode-select -v
    - uses: actions/cache@v2
      with:
        path: |
          .build
          SourcePackages
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    - name: Download dependencies
      run: xcodebuild -resolvePackageDependencies -workspace Clipy.xcworkspace -scheme Clipy -configuration Release -clonedSourcePackagesDirPath SourcePackages
    - name: Build
      run: bash .travis/build.sh
    - name: Prepare Delta
      run: bash .travis/prepare_delta.sh
    - name: Sparkle
      env: 
        SPARKLE_ED25519_KEY: ${{secrets.SPARKLE_ED25519_KEY}}
      run: bash .travis/sparkle_keys.sh
    - name: Show appcast.xml
      run: cat appcast.xml
  test: 
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Show Xcode Version
      run: xcode-select -v
    - uses: actions/cache@v2
      with:
        path: |
          .build
          SourcePackages
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    - name: Download dependencies
      run: xcodebuild -resolvePackageDependencies -workspace Clipy.xcworkspace -scheme Clipy -configuration Release -clonedSourcePackagesDirPath SourcePackages
    - name: Run tests
      run: bash .travis/test.sh
