name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Show Xcode Version
      run: xcode-select -v
    - name: Run tests
      run: bash .travis/test.sh
    - name: Build
    - run: bash .travis/build.sh
